### ISSUE TITLE
Test and implement "additional metrics" from design review

### ISSUE THREAD

**Issue by mdittmer** [GoogleChromeLabs/confluence#39]
These metrics included:

- **Overall API confluence**: what fraction of the total APIs are present in at least 3 or 4 engines at any given time?
- **First to implement**: How many APIs did this browser ship that were later shipped by at least 2 or 3 other browsers?

**Comment by foolip** [comment]
Closing this since Confluence is in maintenance mode. It would be fairly straightforward to compute the N/M metrics though in a one-off fashion, similar to what I did using BCD for a [BlinkOn talk](https://docs.google.com/presentation/d/1_On7g2EAUrVumIZr0PC-_iZszKyGT2_u1HbieThXjKA/edit#slide=id.g5597f85706_4_193).
