### ISSUE TITLE
Firefox data is outdated

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChromeLabs/confluence#463]
The Firefox data seems to be from Firefox 67.  Firefox 68 was released over a month ago.

**Comment by lukebjerring** [comment]
@jugglinmike could you bump us up a version?

**Comment by jugglinmike** [comment]
I could give it a shot. I've never interacted with this project before, though, so I should confirm: did you mean to ask for my help?

**Comment by lukebjerring** [comment]
Nope, false alarm! I'm on my phone and didn't check which project we were lagging. @foolip or @Hexcles are experienced with confluence dashboard.

**Comment by foolip** [comment]
Collecting data and deploying is a manual process. I've done the first part in https://github.com/mdittmer/web-apis/pull/89, will take care of deploying too.

**Comment by foolip** [comment]
Staging instance up at https://confluence-1b8a65f-dot-web-confluence.appspot.com. @bzbarsky can you take a look and see if the data makes no less sense than before? (I saw https://github.com/GoogleChromeLabs/confluence/issues/462, haven't looked into the cause.)

**Comment by bzbarsky** [comment]
@foolip thank you!

The new data says TouchEvent is not supported in Firefox 68 but was supported in Firefox 67.  As far as I know, the implementation status is the same in 67 and 68, on Windows: supported on devices with touch support, not supported (and not exposed on websites) on devices without.

It also looks like the 67 run was on a system without Flash installed while the 68 run is on a system with Flash installed, so some of the `MimeTypeArray`/`Plugin`/`PluginArray` bits are different.

The 68 run has some sort of "__REACT_DEVTOOLS_GLOBAL_HOOK__" thing (that Chrome 76 also has) that 67 does not and that's not a part of Firefox itself as far as I know.

Apart from that, the diffs looks about right.

**Comment by Hexcles** [comment]
@foolip did you collect the results locally? I'm afraid you have the React Developer Tools extension installed in your browser profile(s): __REACT_DEVTOOLS_GLOBAL_HOOK__

**Comment by foolip** [comment]
I collected the Firefox 68 results from BrowserStack, but I have collected data from *some* browser releases on my laptop because they weren't available on BrowserStack yet. https://github.com/mdittmer/web-apis/pull/84 may have been like that, I didn't write in the commit message. 

If I test Firefox 67 and 68 on BrowserStack now, `TouchEvent` and `TouchList` are undefined on both. So collected the data for 67 anew from BrowserStack probably fixes this.

Flash support has changed before, with MimeTypeArray#application/x-shockwave-flash being in Firefox 65 and 66 on Confluence, but not 64 or 67. But this may also be a side effect of Firefox 67 data not being from BrowserStack, I'll recollect and checi.

`__REACT_DEVTOOLS_GLOBAL_HOOK__`, however, is only there on 68. Presumably BrowserStack has installed some extension which adds this. I guess that filtering this whole global out is the best approach.

**Comment by foolip** [comment]
https://confluence-547902c-dot-web-confluence.appspot.com is a new deployment that includes https://github.com/mdittmer/web-apis/pull/91 and https://github.com/GoogleChromeLabs/confluence/pull/469.

I've tested it a bit in Chrome and Firefox, looks good, so I'll go ahead and promote it to prod.

**Comment by foolip** [comment]
Alright, live at https://web-confluence.appspot.com/.
